### PR TITLE
[ui] Work around PySide2 bug affecting property decorators

### LINKED ISSUE #1239: Building and running Meshroom
This thread is a continuation of questions I originally asked [here](https://github.com/alicevision/meshroom/issues/1216#issuecomment-764333032). The proposed solution to my original issue (a faulty camera solve) was to build Meshroom from scratch to pick up a development fix. 

Building and "installing" AliceVIsion (on Windows) according to the current [docs ](https://github.com/alicevision/AliceVision/blob/develop/INSTALL.md) yield an installation that exists in **C:\Program Files\aliceVision**. After a few days of trolling around these issue threads, Google groups, etc., it seems like having a space in the PATH for AliceVision causes troubles. 

I've been able to resolve - _in part_ - the issues I mention in the above thread by wholly moving the AliceVision install into a path that doesn't involve spaces. At least, I think that might be what's helped...troubleshooting this issue is a bit foggy for me. Currently I can get Meshroom launched, but see the following warnings (which I suspect are significant)

> [2021-01-22 08:43:30,198][WARNING] == The following "submitters" plugins could not be loaded ==
>   * simpleFarmSubmitter: No module named 'simpleFarm'
> 
> [2021-01-22 08:43:35,135][WARNING] Missing plugin qtAliceVision.
> [2021-01-22 08:43:35,135][WARNING] Missing plugin qtOIIO.

I can find no definitive information about resolving the above warnings; they exist no matter how much massaging of PATH vars I do. 

Nevertheless, I try to load an EXR image that has no camera metadata. The Release version of Meshroom handles this operation fine. But my development build throws the following errors, and the image fails to load. Might anyone be able to provide advice as to how I might resolve this? :

--------------------

[2021-01-22 08:43:52,961][WARNING] importFilesDialog fileUrls: file:///H:/tmp/plate/plate_cc/plate_cc.0.exr
ERROR: unrecognised option '--useInternalWhiteBalance'
Usage:

AliceVision cameraInit:

Required parameters:
  -i [ --input ] arg                    A SfMData file (*.sfm) [if specified,
                                        --imageFolder cannot be used].
  --imageFolder arg                     Input images folder [if specified,
                                        --input cannot be used].
  -s [ --sensorDatabase ] arg           Camera sensor width database path.
  -o [ --output ] arg (=cameraInit.sfm) Output file path for the new SfMData
                                        file

Optional parameters:
  --defaultFocalLengthPix arg (=-1)     Focal length in pixels. (or '-1' to
                                        unset)
  --defaultFieldOfView arg (=-1)        Empirical value for the field of view
                                        in degree. (or '-1' to unset)
  --defaultIntrinsic arg                Intrinsics Kmatrix "f;0;ppx;0;f;ppy;0;0
                                        ;1".
  --defaultCameraModel arg              Default camera model type (pinhole,
                                        radial1, radial3, brown, fisheye4,
                                        fisheye1).
  --allowedCameraModels arg (=pinhole,radial1,radial3,brown,fisheye4,fisheye1)
                                        Permitted model type (pinhole, radial1,
                                        radial3, brown, fisheye4, fisheye1).
  --groupCameraFallback arg (=folder)   When there is no serial number in the
                                        image metadata, we cannot know if the
                                        images come from the same camera. This
                                        is problematic for grouping images
                                        sharing the same internal camera
                                        settings and we have to decide on a
                                        fallback strategy:
                                         * global: all images may come from a
                                        single device (make/model/focal will
                                        still be a differentiator).
                                         * folder: different folders will be
                                        considered as different devices
                                         * image: consider that each image has
                                        different internal camera parameters
  --viewIdMethod arg (=metadata)        Allows to choose the way the viewID is
                                        generated:
                                         * metadata: Generate viewId from image
                                        metadata.
                                         * filename: Generate viewId from file
                                        names using regex.
  --viewIdRegex arg (=.*?(\d+))         Regex used to catch number used as
                                        viewId in filename.
  --allowSingleView arg (=0)            Allow the program to process a single
                                        view.
                                        Warning: if a single view is process,
                                        the output file can't be use in many
                                        other programs.

Log parameters:
  -v [ --verboseLevel ] arg (=info)     verbosity level (fatal, error, warning,
                                        info, debug, trace).

[2021-01-22 08:44:04,651][ERROR] Error while building intrinsics: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "H:\github\meshroom\meshroom\AliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/me/AppData/Local/Temp/tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\me\AppData\Local\Temp\tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

Traceback (most recent call last):
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 817, in importImagesUrls
    self.importImagesFromFolder(paths)
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 804, in importImagesFromFolder
    self.buildIntrinsics(self.cameraInit, filesByType.images)
  File "H:\github\meshroom\meshroom\ui\reconstruction.py", line 873, in buildIntrinsics
    views, intrinsics = cameraInitCopy.nodeDesc.buildIntrinsics(cameraInitCopy, additionalViews)
  File "H:\github\meshroom\meshroom\nodes\aliceVision\CameraInit.py", line 276, in buildIntrinsics
    proc.returncode, cmd)
RuntimeError: CameraInit failed with error code 1.
Command was: "aliceVision_cameraInit  --sensorDatabase "H:\github\meshroom\meshroom\AliceVision\share\aliceVision\cameraSensors.db" --defaultFieldOfView 45.0 --groupCameraFallback folder --allowedCameraModels pinhole,radial1,radial3,brown,fisheye4,fisheye1 --useInternalWhiteBalance True --viewIdMethod metadata --verboseLevel info --output "C:/Users/me/AppData/Local/Temp/tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282/cameraInit.sfm" --allowSingleView 1 --input "C:\Users\me\AppData\Local\Temp\tmpo7i3rhut/CameraInit/f9436e97e444fa71a05aa5cf7639b206df8ba282//viewpoints.sfm"".

[2021-01-22 08:44:04,688][WARNING] Model size of -5245 is less than 0
[2021-01-22 08:44:04,708][WARNING] Model size of -825 is less than 0

### PR DESCRIPTION
**Pull request by p12tic**
## Description

PySide 5.15.1 and newer have a bug (https://bugreports.qt.io/browse/PYSIDE-1426) which results in the following error emitted on certain @Property decorators:

```
TypeError: A constant property cannot have a WRITE method or a NOTIFY signal.
```

Until the bug is fixed on PySide2 side workaround is to not use Property as a decorator, but as a simple function wrapper emitting the property as a class member.

Fixes #1239.

### CODE REVIEW

**Comment by fabiencastan** [comment]
Is it still compatible with 5.14.1? If yes, I have no pbl to merge it.

**Comment by p12tic** [comment]
@fabiencastan I've checked that this PR works on PySide 5.14.1.

**Comment by p12tic** [comment]
@fabiencastan Just a friendly ping :-)

**Review by cbentejac — APPROVED** [review]

**Comment by fabiencastan** [comment]
Thanks @p12tic !

**Pull request merged**
