### PR TITLE
[WIP] depth mask node

### PR DESCRIPTION
**Pull request by ALfuhrmann**
## Description

**DepthMaskFilter** implements a simple way to mask unwanted areas of the input images.
When using a neutral background, depthmasks may extend artifacts into the background 
see also #566 and #188 

## Features list
uses black/white images to mask unwanted input image areas
masks have to be generated externally (WIP), all black (=0) areas are ignored, >0 is used

## Usage
**Node inputs:**
_Input_: cameraInit.sfm for input image file names (.sfm only, no alembic)
_Filtered Depth Maps Folder_: depth maps folder output of DepthMaskFilter
_Mask Folder_: folder containing b/w mask .PNG  images with the same names as the associated input files
The masks have to be rectified, so you cannot use your generated masks directly, but have to run them through a _PrepareDenseScene_ node. See https://github.com/alicevision/meshroom/issues/566#issuecomment-527447307.

## Implementation remarks
This is a simple implementation as a Python script, no optimizations whatsoever.

This keeps the implementation short, but it means that I have a lot of additional dependencies:
I had to add numpy, Pillow, Imath, and OpenEXR. (OpenEXR does not install with pip on windows, I had to use a pre-compiled version from https://www.lfd.uci.edu/~gohlke/pythonlibs/)

An additional node I am working on, which generates using background subtraction & floodfill, additionally needs OpenCV.

So I do not know if this would be acceptable for you guys. Implementing these nodes in C++ would not be much of a problem, but since they only take a few seconds to run I used Python for the time being.

RFC, Tony

### CODE REVIEW

**Comment by aarahvar** [comment]
Thanks for your files. Could you please explain how your code should be integrated with Meshroom?
I generated the .pyc file and put it in the folder \lib\meshroom\nodes\aliceVision beside other node files, but meshroon does not recognize it.
What should I do with  requirements.txt file?

Thanks for your help.

**Comment by natowi** [comment]
@aarahvar you need to install the requirements using pip and then you can compile Meshroom (python setup.py build) or start Meshroom without compiling as described [here](https://github.com/natowi/meshroom_external_plugins).

**Comment by ALfuhrmann** [comment]
@aarahvar alternatively, if you want to avoid building meshroom, you could try it [this way](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623).

**Comment by aarahvar** [comment]
@ALfuhrmann 

Anyway, I used the second suggestion of @natowi and ran Meshroon with DepthMaskFilter. However, before computing of this node, PrepareDenseScene_2 failed as follows (it happens immediately after starting its computing)! Do you have any idea?
I set the input of imageFolders as the address of the mask folder.

Program called with the following parameters:
 * evCorrection = 0
 * imagesFolders =  = [C:/Users/Amir/Desktop/Canon/2019_11_12/TIFF/Mask]
 * input = "C:/Users/Amir/Desktop/Meshroom/MeshroomCache/StructureFromMotion/e0245e18cb2c00a813db558e615b979e8292a5aa/sfm.abc"
 * output = "C:/Users/Amir/Desktop/Meshroom/MeshroomCache/PrepareDenseScene/14ca8b3755d69dc3bcb5f2c4c0c3659369820a27"
 * outputFileType = "exr"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[00:55:54.980410][info] median Ev : 5.78577e-39

**Comment by ALfuhrmann** [comment]
@aarahvar are you sure the [masks are PNGs](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623)?

From your path it looks like you used TIFFs.

**Comment by aarahvar** [comment]
> 
> 
> @aarahvar are you sure the [masks are PNGs](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623)?
> 
> From your path it looks like you used TIFFs.

Yes, They are PNG. TIFF is the name of the main folder (the original images for 3d reconstruction are TIFF format.)

**Comment by aarahvar** [comment]
> 
> 
> @aarahvar are you sure the [masks are PNGs](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623)?
> 
> From your path it looks like you used TIFFs.

Is there any difference between .png and .PNG? Mine are .png. I'll try with PNG now.

**Comment by aarahvar** [comment]
> 
> 
> @aarahvar are you sure the [masks are PNGs](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623)?
> 
> From your path it looks like you used TIFFs.

@ALfuhrmann 
Is there any difference between .png and .PNG?
Mine are .pmg!

**Comment by aarahvar** [comment]
> 
> 
> > @aarahvar are you sure the [masks are PNGs](https://github.com/alicevision/meshroom/issues/566#issuecomment-527822623)?
> > From your path it looks like you used TIFFs.
> 
> @ALfuhrmann
> Is there any difference between .png and .PNG? Mine are .png. I'll try with PNG now.

No, .PNG failed as well!

**Comment by ALfuhrmann** [comment]
".pmg" is a typo, I hope.

I really can't say what's wrong, the PrepareDenseScene node is a standard meshroom node which corrects the lens distortion of input images. It is in there so that the masks fit to the images. I did not change it.

If the StructurFromMotion delivers results and your folder contains the correct masks as .png, I have no idea why this does not work. Maybe try this part of the graph with an unmodified meshroom installation.

**Comment by aarahvar** [comment]
> 
> 
> ".pmg" is a typo, I hope.
> 
> I really can't say what's wrong, the PrepareDenseScene node is a standard meshroom node which corrects the lens distortion of input images. It is in there so that the masks fit to the images. I did not change it.
> 
> If the StructurFromMotion delivers results and your folder contains the correct masks as .png, I have no idea why this does not work. Maybe try this part of the graph with an unmodified meshroom installation.

It fails even in the unmodified Meshroom. Maybe something is wrong in PNG format!!!
How did you make the png files yourself?

**Comment by natowi** [comment]
@aarahvar You could test images and masks from https://github.com/BritishMuseumDH/prudhoeLionLeft/tree/master/images

**Comment by aarahvar** [comment]
> 
> 
> @aarahvar You could test images and masks from https://github.com/BritishMuseumDH/prudhoeLionLeft/tree/master/images

I checked both with unmodified Meshrooms 2019.1.0 and 2019.2.0 with your suggested dataset and both failed. As long as I assing the folder of masks to the ImageFolders input of the PrepareDenseScene node, it fails!

**Comment by aarahvar** [comment]
@natowi 

I realized that the names of the masked files in your suggested dataset were different than the original photos. After changing the names, PrepareDenseScene node worked properly. So I can conclude that something is wrong with my masked files!
Thanks for your help.

**Comment by aarahvar** [comment]
@ALfuhrmann 

After resolving the problem of PrepareDenseScene_2 , I computed DepthMaskFilter, but it fails immediately without any log! 
I used your alternative way for integrating the plugin (I replaced OpenEXR with a compatible version of mine) as well as @natowi 's approach. None of them worked.

image

**Comment by natowi** [comment]
@aarahvar Did you set your path to the masks in the PrepareDenseScene2 node under ImagesFolder?
Anyway, I will put a sample project together.

**Comment by aarahvar** [comment]
> 
> 
> @aarahvar Did you set your path to the masks in the PrepareDenseScene2 node under ImagesFolder?
> Anyway, here is a sample project I put together:
> 
> [masking-example-2019.2.zip](https://github.com/alicevision/meshroom/files/3853058/masking-example-2019.2.zip)

@natowi 
Your help is appreciated. Your project works for me. Then I loaded my photos and masks to your project. But PrepareDenseScene2 fails as follows:

`Program called with the following parameters:
 * evCorrection = 0
 * imagesFolders =  = [C:/Users/Amir/Desktop/Canon/2019_11_12/TIFF/Mask/MASK3]
 * input = "C:/Users/Amir/Desktop/alaki/masking-example-2019.2/MeshroomCache/StructureFromMotion/b14efd28b29176c16ecb5072169c0ebe75b0fe5b/sfm.abc"
 * output = "C:/Users/Amir/Desktop/alaki/masking-example-2019.2/MeshroomCache/PrepareDenseScene/09cf2ac05e12bee092042321aac5acf3aaf1cfcd"
 * outputFileType = "png"
 * rangeSize = 40
 * rangeStart = 0
 * saveMatricesTxtFiles = 0
 * saveMetadata = 1
 * verboseLevel = "info"

[00:44:59.076051][warning] Cannot save informations in images metadata.
Choose '.exr' file type if you want AliceVision custom metadata
Exporting Scene Undistorted Images
0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
[00:44:59.085881][info] median Ev : -1.17829e-24
libpng error: known incorrect sRGB profile
libpng error: known incorrect sRGB profile
libpng error: known incorrect sRGB profile
`

Something should be wrong in my PNG format. I tried many things, something like [this](https://stackoverflow.com/questions/22745076/libpng-warning-iccp-known-incorrect-srgb-profile), but all of them failed!

**Comment by aarahvar** [comment]
Finally, I got the result. Indeed, when I load my masked images to meshroom, meshroom fails in PrepareDenseScene2 . But when I load my unmasked (original) photos, it works. **Do you know why?** I prefer to load masked photos because I waste lots of time on the processing of some areas that will be masked later!

**Comment by ALfuhrmann** [comment]
Hm. You seem to have a wrong color profile in your PNGs. Have you tried running them through any kind of processing, e.g. imagemagick or GIMP?

When you say "all of them failed", do you mean the result did not change, or the other tools could not read them, either?

In what tool did you create them?

**Comment by tpontin** [comment]
image

To get consistent results, I had to add an if file exists for mask_name on this line.
Since the node takes cameraInit.sfm to create the loop for processing the masks, but ImageMasking module only processes images that are placed in SFM node, an error can occur in datasets where not every image is placed.

There may be a more robust way of achieving the same thing, but this seems to be working for me for now.

Adjusted code: 
if os.path.exists(mask_name): self.maskEXR(depth_map_name, mask_name, -1.0)

**Comment by fabiencastan** [comment]
The PR https://github.com/alicevision/meshroom/pull/708 has been integrated and will be part of the next release. It provides a c++ implementation of the feature described here.
So I'm closing this PR.

**Pull request closed without merging**
