### PR TITLE
[WIP] Add file type selection for dense point cloud

### PR DESCRIPTION
**Pull request by natowi**
## Description

This will (hopefully) add file type selection for dense point cloud

https://github.com/alicevision/meshroom/issues/690

https://github.com/alicevision/AliceVision/pull/597

## Implementation remarks

ToDo: 

[ ] find a way to exclude the file type drop down from the class
[ ] include rawPointCloud file type

### CODE REVIEW

**Comment by natowi** [comment]
Is there a reason for using "{cache}/{nodeType}/{uid0}/mesh.obj" in outputMesh instead of desc.Node.internalFolder ?

**Comment by natowi** [comment]
The PR note by @gregoire-dl says "This PR adds the possibility to export a dense point cloud as a SfMData file (.abc, .json, ...)", but the CLI does not provide this option. (Attaching the desired file type does work, but is not documented. The note `"Output SfMData filename (.json, .bin, .xml, .ply, .baf"` was replaced by `"Output point cloud with visibilities as SfMData file."` with the last PR).

For me it looks like the main_convertSfMFormat.cpp needs to be modified for my MR PR to work.

I think there is no option for the file type defined yet - or am I missing something?
(c++ is new for me)

At the moment there is only
`std::string outputSfMDataFilename;`

Do we have to add something like:

`std::string outputSfMDataFilename = sfmDataIO::Save(sfmDataIO::FileType::ABC);`

 ```
// user optional parameters

("outputSfMDataFilename", po::value<std::string>(&outSfMDataFilename)->default_value(outSfMDataFilename),
          sfmDataIO::Save(sfmData, outputSfMDataFilename, sfmDataIO::ESfMData(flags)),
      "Output SfMData filename (.abc, .json, .bin, .xml, .ply, .baf)"
```

/ I also noted exportPointCloud((outDirectory/"densePointCloud_raw.abc") is hardcoded

**Comment by fabiencastan** [comment]
> Is there a reason for using "{cache}/{nodeType}/{uid0}/mesh.obj" in outputMesh instead of desc.Node.internalFolder ?
No you could do:
`            value=desc.Node.internalFolder + 'mesh.obj',`

**Comment by fabiencastan** [comment]
> I think there is no option for the file type defined yet - or am I missing something?

The file type is just defined by the file extension, so there is no need for an extra argument.

**Comment by natowi** [comment]
> extension

I tried my PR running MR from CLI, but get the following error when computing the Meshing node:

```
[2019-11-04 10:42:06,376][ERROR] Error on node computation: Error on node "Meshing_1":
Log:
ERROR: unrecognised option '--outputSfMDataFilename'
```

**Comment by fabiencastan** [comment]
See the existing parameters here:
https://github.com/alicevision/AliceVision/blob/develop/src/software/pipeline/main_meshing.cpp#L157

**Comment by natowi** [comment]
Ah, so it is outputDensePointCloud and not outputSfMDataFilename

**Comment by natowi** [comment]
At the moment the drop down selector is in
```
class Meshing(desc.CommandLineNode):
    commandLine = 'aliceVision_meshing {allParams}'
```
This results in the unrecognized option error...

**Comment by natowi** [comment]
This is a workaround for those who want to change the file type in the gui:

add 
```
desc.File(
            name="output",
            label="Output Dense Point Cloud",
            description="Output dense point cloud('abc', 'ply', 'json', 'xml', 'baf', 'bin').",
			value='',
            uid=[],
        ),
```
as last entry within `inputs = [       ]`
This allows for a custom path to be defined for the dense point cloud.

@fabiencastan Is it possible to allow editing the paths in `outputs = [       ]` as it is possible for inputs or is there another solution for changing the file type in nodes who do not have a cli expression for the file type? I did not find a way for the drop down menu to not be recognized as cli option. Any hints?

**Comment by natowi** [comment]
From what I learned from https://github.com/alicevision/meshroom/issues/697 I guess I could exclude the select file type option from the cli commands, but now I need the -- .

What is the correct syntax to replace _{allParams}_ with a list of the supported parameters (excluding outputDenseFileType)?

```
class Meshing(desc.CommandLineNode):
    commandLine = 'aliceVision_meshing {allParams}'
```

**Comment by natowi** [comment]
Ok I figured it out:

```
class Meshing(desc.CommandLineNode):
    commandLine = 'aliceVision_meshing --input {inputValue}
``` 

This way it should be possible to list only the supported options.

**Comment by natowi** [comment]
Remaining problem: Texturing node expects .abc input format

**Comment by fabiencastan** [comment]
Don't modify the full pipeline to use another file format, just use ConvertSfM where you need to convert your Alembic file to something else.

**Comment by fabiencastan** [comment]
Most of the file formats are not able to store all the information we need: cameras, visibilities, etc.
For instance, PLY is only able to deal with point clouds without extra-attributes.

**Comment by natowi** [comment]
I have tried convert sfm but it does not work with the densepointcloud.abc as input. The resulting ply is 1kb in size

**Comment by fabiencastan** [comment]
Maybe some feature types are not enabled on the ConvertSfMFormat?
In all case, it's supposed to work: either it is a parameter problem or a bug.

**Comment by natowi** [comment]
StructureFromMotion sfm.abc -> ConvertSfMFormat will convert the whole pointcloud

Meshing densePointCloud.abc -> ConvertSfMFormat will only convert the cameras and dismiss the pointcloud

**Comment by fabiencastan** [comment]
You should check the "unknown" descriptor type as the points have been created by the depth maps without the notion of feature/descriptor.

**Comment by natowi** [comment]
There is no "unknown" descriptor option in the cli or gui. I unselected sift but this does not work.

**Pull request closed without merging**
